services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopify-rest-api
    container_name: shopify-rest-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    # networks:
    #   - shopify-net
    volumes:
      - /usr/src/app/node_modules
      # NOTE: jangan pernah save code di volume
      # perubahan codemu tidak akan pernah berubah di container
      # - .:/usr/src/app
    depends_on:
      - mongodb

  # service name sama container name usahakan sama, biar nggk pusing
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: shopify
      MONGO_INITDB_ROOT_PASSWORD: secret
    # networks:
    #   - shopify-net

# NOTE: network aku matikan, bisa jadi setupnya salah, sementara pakai global network
# case network untuk level security
# networks:
#   shopify-net:
#     driver: bridge
